services:
    _defaults:
        autowire: true
        autoconfigure: true
    CQRS\:
        resource: '../../../src/'
        exclude:
            - '../../../src/DependencyInjection/'
            - '../../../src/Tests/'

    CQRS\Controller\CommandController:
        tags: [controller.service_arguments]

    CQRS\Routing\CommandsLoader:
        tags: [routing.loader]
